### PR TITLE
Remove jQuery

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
This is an automated PR from: https://github.com/NullVoxPopuli/ember-jSquirrels

     In an effort to better ready the Ember ecosystem for the modern web, jQuery must be removed.

     There have been native replacements for jQuery APIs for quite a few years.

     Removing jQuery will reduce everyone's app vendor size by 30-80kb after min+gzip, depending on the jQuery version.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
I wonder if I should be running the qunit moduleFor codemod first. hmm

**Comment by jgwhite** [comment]
@ygongdev @H1D mind taking a look at this?

**Comment by ygongdev** [comment]
I’ve been doing some work on this related to tests. The test helpers will rely on jquery syntax. And it has been hard for me to find the equivalent replacement. Are we expecting to land this change on master or release before 2.x.x?

**Comment by NullVoxPopuli** [comment]
@ygongdev where are the helpers that rely on jQuery?

even if the codemod didn't do it correctly, I know what traslations are (and need to upstream those to the codemod)

**Comment by ygongdev** [comment]
@NullVoxPopuli IIRC you can pass `jquery` fns to `reorder`, e.g `:contains`. I couldn't find a replacement for that. 
Reference PR: #271

**Comment by NullVoxPopuli** [comment]
@ygongdev I found this: https://github.com/nefe/You-Dont-Need-jQuery#query-selector

idk how open you'd be to that

```ts
// jQuery
$("selector:contains('text')");

// Native
function contains(selector, text) {
  var elements = document.querySelectorAll(selector);
  return Array.from(elements).filter(function(element) {
    return RegExp(text).test(element.textContent);
  });
}
```

**Comment by ygongdev** [comment]
@NullVoxPopuli do you want to try the codemod again? 😬

**Comment by NullVoxPopuli** [comment]
still need to PR to here: https://github.com/ember-codemods/ember-3x-codemods/tree/master/transforms/jquery-apis
to support contains

**Comment by ygongdev** [comment]
That should be no longer necessary for this repo. I've removed our dependency on `contains` with native JS API

**Comment by ygongdev** [comment]
Should be solved in #324

**Pull request closed without merging**
