### PR TITLE
Allow @ember/test-helpers 3

### PR DESCRIPTION
**Pull request by francois2metz**
@ember/test-helpers v3 has been released for a while.

### CODE REVIEW

**Comment by francois2metz** [comment]
Not sure which pnpm version was used to generate the lockfile.  I setup pnpm@7.33.6, instead of the last one 8. It should works now.

**Comment by francois2metz** [comment]
I fixed a small when running tests with @ember/test-helpers v3. Should be good now!

**Comment by francois2metz** [comment]
Is there is any chance to merge it?

**Review by knownasilya — APPROVED** [review]

**Comment by knownasilya** [comment]
@francois2metz should it pass in ember-release?

**Comment by knownasilya** [comment]
Rerunning the tests made it pass, and it didn't seem related to your changes.

**Comment by KroneckerDeIta** [comment]
Can a release with these changes be published please? I am upgrading my project to Ember 5.4 and I am having to put the following into my package.json file so that an npm install goes through:

    "overrides": {
        "ember-sortable": {
            "@ember/test-helpers": "^3.2.0",
            "ember-source": "~5.4.0"
        }
    }

**Pull request merged**
