### PR TITLE
Fix deprecation warning `Importing from ember-test-waiters is deprecated`

### PR DESCRIPTION
**Pull request by charlesfries**

### CODE REVIEW

**Comment by ygongdev** [comment]
Thanks for the PR. Can you also remove `ember-test-waiters` from our `package.json`?

**Comment by ygongdev** [comment]
Can you try removing it outright and then `ember install @ember/test-waiters`. Idk if the package is still `ember-test-waiters` or `@ember/test-waiters`.

**Comment by charlesfries** [comment]
Pushed

**Comment by ygongdev** [comment]
@charlesfries looks like the tests are failing b/c of `yarn.lock`. Can you `yarn install` and push your `yarn.lock` file? Thanks!

**Comment by charlesfries** [comment]
Third time's a charm. Pushed

**Comment by ygongdev** [comment]
3.20 is flaky, so no worries. Thanks!

**Pull request merged**
