### PR TITLE
Added check for transitionDuration to isAnimated

### PR DESCRIPTION
**Pull request by cah-briangantzler**
Fixes https://github.com/adopted-ember-addons/ember-sortable/issues/231

### CODE REVIEW

**Comment by ygongdev** [comment]
@cah-briangantzler, looks good so far! Just a couple of questions from my end.

1. Are we able to visually confirm that this fixes #231? e.g it works after removing the transition from css.
2. I see that you write a nice unit test for `isAnimated`, which is awesome. Are we able to take it one step further and write an integration or smoke test that fails #231 without your change and passes with your change?

Just to ensure that we have this case covered in the future.
Thanks for your hard work!

**Comment by cah-briangantzler** [comment]
I actually did have that as an acceptance  test and then removed it. The problem was from the test it was not obvious what and how the test was working. Second for a failure, the promise never returns, so the test just stalled, the promise never resolved. Wasnt sure how to timeout waiting on a promise and fail the promise.

So long or short, I had a test, it stalled, when I put the fix in it completed normally.

**Comment by cah-briangantzler** [comment]
Also, now that Im thinking about it, you cant run a test with the change and a test without the change,. The code is either there or it isnt. This fix is to stop a bad thing from happening. Once its fixed, you cant make the bad thing happen, thats the point, so dont know you can make a failing test

**Comment by ygongdev** [comment]
Oh, sorry I should make it clear. I didn't expect to have both failing test and working test.
I was hoping that the current passing test after your change was failing before your change, so it verifies that the bug has been fixed.

**Comment by cah-briangantzler** [comment]
Yes. It wasnt so much failing as no completing, but yes I did have that. But it wasnt really obvious what was being tested. Can add it back easy enough. An then you can decide if it actually conveys anything

**Comment by cah-briangantzler** [comment]
Just added and pushed. If you clone repo, go into this branch, undo the one line in sortable-item and run the new test, it will hang, put the line back and it will complete. But the test itself looks like a duplicate and its not immediately obvious what the test is doing. It just looks like an extra test. Added a few comments to help.

**Comment by cah-briangantzler** [comment]
Ill take a look at this later tonight (EST here). These tests pass locally. The test I wrote is passing now, but another test is failing that shouldnt be effected. Will check it out

**Comment by ygongdev** [comment]
LGTM, thanks!

**Comment by sean-realestate** [comment]
Can you guys make a new publish base on this commit please? Seems like the latest version does not have this change.

**Comment by ygongdev** [comment]
@sean-realestate sure, but just want to confirm if this PR will address your use case?

**Comment by sean-realestate** [comment]
> @sean-realestate sure, but just want to confirm if this PR will address your use case?

I believe so. Version 2.1.1 does not work for me. After I use the change of this PR, the addon worked.

**Comment by ygongdev** [comment]
@sean-realestate 👍 I just released `2.1.2` with this change.

**Pull request merged**
