### PR TITLE
Removed the component version

### PR DESCRIPTION
**Pull request by cah-briangantzler**
Breaking Change !!!

Since 2.2.0 has been released with both component and modifier (Although I would have liked to see the component version deprecated instead of just mentioned in readme) this PR removes the component version.  It does not update the readme as there is another PR pending that does that

### CODE REVIEW

**Comment by ygongdev** [comment]
Looks like tests are failing. Since we only have modifiers in this PR, we should look into stabilizing the tests.

**Comment by cah-briangantzler** [comment]
I removed the component integration tests, looks like I missed the component acceptance tests. Sorry, will fix that

**Comment by cah-briangantzler** [comment]
So whats the difference between the tests and the one with floating dependancies? I dont know why tests would pass and floating would fail one.

**Comment by ygongdev** [comment]
I'm actually not sure but it looks like the floating dependencies are missing the `yarn install` and `yarn lint` step. I wonder if that means something like `yarn.lock` needs to be updated?

**Comment by cah-briangantzler** [comment]
running yarn install did not update the yarn.lock

**Comment by ygongdev** [comment]
Mmm, I dug into the past failures. It could be a flaky or legit test failure for `Acceptance | smoke modifier: reordering with mouse events` for Firefox.

**Comment by ygongdev** [comment]
@jgwhite Sorry to bother you, but do you remember what the intention behind the  "Floating dependencies" test is meant to test for?

**Comment by jgwhite** [comment]
> @jgwhite Sorry to bother you, but do you remember what the intention behind the  "Floating dependencies" test is meant to test for?

I have no idea. Sorry!

**Comment by cah-briangantzler** [comment]
Looking into it more it looks like it runs the tests without the yarn lock. To see if it runs with the most recent versions.

However, for an addon, there is no reason to use a yarn lock. When the addon is consumed in the application, its the applications yarn.lock that applies, the one in the addon is ignored isnt it?

That being said, let me try running locally with no yarn lock and see what I get.

**Comment by cah-briangantzler** [comment]
This https://github.com/adopted-ember-addons/ember-sortable/pull/380 should be vetted and merged and another release before merging in removing components

**Comment by cah-briangantzler** [comment]
Ok so without a yarn.lock I get no failures when running `ember t -s` however do get the one failure when running `ember t`.  I notice that without the yarn.lock we are getting all the errors `WARN: DEPRECATION: setSourceDestroying is deprecated, use the destroy() API to destroy the object directly` which you can refer to https://github.com/kaliber5/ember-bootstrap/pull/1143

**Comment by snewcomer** [comment]
@cah-briangantzler Mind merging master?  We are close to ready for a major version bump

**Comment by cah-briangantzler** [comment]
rebased, push, rebuilding now

**Comment by snewcomer** [comment]
@cah-briangantzler This looks great!  Mind updating the README as well?

**Comment by cah-briangantzler** [comment]
Updated.

**Review by jacojoubert — APPROVED** [review]

**Review by snewcomer — APPROVED** [review]
ref https://github.com/adopted-ember-addons/ember-sortable/commit/ffbd488b745f41ba4077e7e8d37410b247e89435

**Comment by kiwiupover** [comment]
We are not going to release the new version until we have the tests passing on ember 3.20, 3.24, and 3.28 PRs for those changes will follow. #450

**Comment by kiwiupover** [comment]
@cah-briangantzler thanks heaps for pushing this work forward.

**Comment by bjornharrtell** [comment]
This was not noted as a breaking change at https://github.com/adopted-ember-addons/ember-sortable/blob/master/CHANGELOG.md#v300-2021-11-29, I guess it should be?

**Pull request merged**
