### PR TITLE
Create github_ci.yml

### PR DESCRIPTION
**Pull request by ygongdev**
Testing out github actions ci

### CODE REVIEW

**Comment by ygongdev** [comment]
@cah-briangantzler FYI, I think there might be some legitimate test failures, I'd like to fix our CI before accepting new PRs. Sorry for the delays.

**Comment by cah-briangantzler** [comment]
Should fix the getWithDefault to make it easier to read the tests and fine the failures

**Comment by ygongdev** [comment]
Yeah, but I actually don't think we're using any `getWithDefault` in the codebase?

**Comment by ygongdev** [comment]
seems like it's coming from a 3rd party repo https://github.com/simplabs/ember-test-selectors/pull/587

**Pull request merged**
