### PR TITLE
Closest polyfill

### PR DESCRIPTION
**Pull request by ygongdev**
1.  Adding closest polyfill
2. Adding downloads badge

Manually tested on IE11.
Addresses #241

### CODE REVIEW

**Comment by btecu** [comment]
@ygongdev you didn't have to polyfill `matches`, just `closes`:
```
  if (!Element.prototype.closest) {
    Element.prototype.closest = function(selector) {
      let element = this;

      do {
        if (element.msMatchesSelector(selector)) {
          return element;
        }

        element = element.parentElement || element.parentNode;
      } while (element !== null && element.nodeType === 1);

      return null;
    };
  }
```

**Comment by ygongdev** [comment]
Oh ok, I will remove the matches polyfill

**Comment by btecu** [comment]
You have to update the `closest` as well, to use `msMatchesSelector`  - `(element.msMatchesSelector(selector)`, since we're literally putting this polyfill in place for IE.

**Comment by ygongdev** [comment]
@btecu We don't need to make specific distinction right? As in, `element.matches` should be fine, since we're targeting `closest`, not `matches`? Doing so would make other non IE browsers use `msMatchesSelector`

**Comment by btecu** [comment]
The non IE browsers already implement `matches` so `if (!Element.prototype.closest) {` prevents us from overriding their `matches` implementation.

**Pull request merged**
