### PR TITLE
Fix changelog

### PR DESCRIPTION
**Pull request by sandstrom**
Minor text issues

### CODE REVIEW

**Comment by kiwiupover** [comment]
@sandstrom Are you still interested in landing this PR?

**Comment by sandstrom** [comment]
@kiwiupover Sure!

**Comment by sandstrom** [comment]
But unless there is someone that can merge it I don't think it'll happen.

When I added this PR there wasn't any merge conflicts afaik, so I guess they've appeared because it took a long time for anyone to act on it.

So if I update the PR to remove the conflicts, will anyone merge it?

**Comment by kiwiupover** [comment]
@sandstrom I will merge it

**Comment by sandstrom** [comment]
@kiwiupover I've added https://github.com/adopted-ember-addons/ember-sortable/pull/475

**Pull request closed without merging**
