### PR TITLE
Upgraded ember-modifier to 2.1.0

### PR DESCRIPTION
**Pull request by cah-briangantzler**
Fixes https://github.com/adopted-ember-addons/ember-sortable/issues/383

### CODE REVIEW

**Comment by btecu** [comment]
*`2.1.0`

If the test failure is related, could also try `1.0.5`: https://github.com/ember-modifier/ember-modifier/releases/tag/v1.0.5

**Comment by lukemelia** [comment]
FWIW, tests are passing for me locally.

**Comment by ygongdev** [comment]
@cah-briangantzler Mind fixing the merge conflicts, so I can merge this?

**Comment by cah-briangantzler** [comment]
Fixed, tests running

**Pull request merged**
